#!/bin/bash  

echo "hello world"

read name
echo "Hi $name"

if [ "$name" = "Naveen" ]; then
  echo "Hello, Naveen"
else
  echo "Who are you?"
fi

for i in 1 2 3; do
  echo "name $i"
done

count=1
while [ $count -le 5 ]; do
  echo $count
  ((count++))
done

