#!/bin/bash

AMI_ID="ami-09c813fb71547fc4f"
SG_ID="sg-032c5ed4c7e550e18"
INSTANCES=("frontend" "mongodb" "catalogue" "redis" "user" "cart" "mysql" "rabbitmq" "shipping" "dispatch" "payment")
ZONE_ID="Z06966282ETBPQYP576KM"
DOMAIN_NAME="devops84.store"

for instance in ${INSTANCES[@]}
do
    INSTANCE_ID=$(aws ec2 run-instances --image-id ami-09c813fb71547fc4f --instance-type t3.micro --security-group-ids sg-032c5ed4c7e550e18 --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$instance}]" --query "Instances[0].InstanceId" --output text)
    if [ $instance != "frontend" ]
    then
      IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)
    else 
      IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
    fi
    echo "$instance IP address: $IP"

    aws route53 change-resource-record-sets \
  --hosted-zone-id $ZONE_ID \
  --change-batch '
  {
    "Comment": "Creating or updating a record set for cognito endpoit",
    "Changes": [{
    "Action"           : "UPSERT",
    "ResourceRecordSet": {
    "Name"             : "'$instance','$DOMAIN_NAME'",
    "Type"             : "A",
    "TTL": 1,
    "ResourceRecords"  : [{
    "Value"            : "'$IP'"
     }]
   }
   }]
  }'
done
