#!/bin/bash

AMI_ID="ami-09c813fb71547fc4f"
SG_ID="sg-032c5ed4c7e550e18"
INSTANCES=("frontend" "mongodb" "catalogue" "redis" "user" "cart" "mysql" "rabbitmq" "shipping" "dispatch" "payment")
ZONE_ID="Z06966282ETBPQYP576KM"
DOMAIN_NAME="www.devops84.store."

if [ $instance != "frontend" ]
    then
      IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)
    else 
      IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
    fi
    echo "$instances IP address: $IP"

aws route53 change-resource-record-sets \
  --hosted-zone-id $ZONE_ID \
  --change-batch '
  {
    "Comment": "Creating or updating a record set for cognito endpoint"
    ,"Changes": [{
    "Action"           : "CREATE"
    ,"ResourceRecordSet" : {
       "Name"             : "'$INSTANCES'.'$DOMAIN_NAME'"
       ,"Type"             : "A"
       ,"TTL"              : 1
       ,"ResourceRecords"  : [{
         "Value"            : "'$IP'"
     }]
   }
   }]
  }'